### ISSUE TITLE
auto answer

### ISSUE THREAD

**Issue by ernany** [grahambrown11/buzz-star#16]
The ability to activate automatic answering

**Comment by grahambrown11** [comment]
Hi @ernany thanks for your interest, what do you mean by auto answer?
Would you like all inbound calls to automatically answer?

**Comment by ernany** [comment]
hello congratulations on the projec. that's right, it would be interesting a configuration that allows this

**Comment by grahambrown11** [comment]
@ernany I've just released [v1.3.0](https://github.com/grahambrown11/buzz-star/releases/tag/v1.3.0) which now has this option 🎉. It may take some time to get approved by Google as I've included the idle api permission to ensure the user is active before auto answering, hopefully it'll be available in a few days. Hope this is what you were looking for 😄
