### ISSUE TITLE
Buzz pops but it does not display the keypad (numbers)

### ISSUE THREAD

**Issue by lambertlu** [grahambrown11/buzz-star#29]
When we launch Buzz, enter all required information and save settings then go to the Chrome Ext, we disable and re-enable it.
Buzz pops but it does not display the keypad (numbers) it’s just blank with a black background.
![cb5a6d7d6e0444f7b788f1efe6954246](https://user-images.githubusercontent.com/7459581/164734181-695b29ad-fe29-40ef-af00-1d5fc9967279.png)

OS: Ubuntu 18.04 LTS
Chrome version: google-chrome-stable_99.0.4844.51-1_amd64.deb

Thanks!

**Comment by grahambrown11** [comment]
Hi @lambertlu you have to have at least a Host & Extension set in the settings for the login button to appear, once logged in then you'll see the numeric pad.
(if they are grey in colour and have the following placeholder values `pbx.local` and `extn` then Buzz* has not been configured)
