### ISSUE TITLE
Turn off the ringer 

### ISSUE THREAD

**Issue by Buzzext** [grahambrown11/buzz-star#36]
I work for a company that uses this daily for incoming calls. Please give us a way to turn off the ring output. Imagine having to listen to that ring come into your headset 100 times a day. On behalf of hundreds of employees thanks in advance.

**Comment by grahambrown11** [comment]
I am glad to hear that you have found this extension useful.
If the agents use a web CRM and a script can be injected into that you can use the [API](https://github.com/grahambrown11/buzz-star/wiki/API-Integration) to auto answer then the ringing will be skipped - that is how we implemented for our call centre.
I realise there are no examples for the API so I'll work on that.
I'll add another option for the ringing sound, maybe a beep - I feel there needs to be an audible indication there is an incoming call.
Unfortunately I don't have much time on my hands at the moment, I will try my best to get to it in the next 2 weeks

**Comment by grahambrown11** [comment]
I've released a new version with 3 extra ringtones to choose from - hope that helps
