### ISSUE TITLE
Buzz phone not connecting calls completely

### ISSUE THREAD

**Issue by mustang31489** [grahambrown11/buzz-star#41]
Buzz does incomplete first ring and the call is dropped. Resulting in a missed call in our company logs. This issue will happen several times in a row.

**Comment by grahambrown11** [comment]
If you enable developer mode in Chrome Extension section then you'll get an `Inspect views` option and if you share the logs from the `offscreen.html` maybe I can assist...
I would assume it has something to do with the connectivity between the client browser and Asterisk - are they on the same LAN or going over the Internet?

**Comment by grahambrown11** [comment]
closting due to no response
